#!/bin/bash
estadisticas_vm()
{
	clear
	while true;
	do
		#Esto busca todas las máquinas que tengas creadas en VBOX
		VBoxManage list -s vms | cut -d '"' -f 2 > maquinas.txt
		typeset -a Menu
		exec 3< ./maquinas.txt
		Contador=1
		echo -e "\e[31m"
		while read linea <&3; do
			echo "$Contador- $linea"
			Menu[$Contador]="$linea"		# Añadimos elementos al array
			Contador=$((Contador+1))	
		done
		echo "0- Salir"
		echo ""
		echo "Seleccione una Maquina Virtual."
		read opcion
		if [ $opcion -eq 0 ];
		then
			echo -e "\e[0m"
			break
		elif [ $opcion -ge 1 -a $opcion -le ${#Menu[*]} ];
		then
			#Esto hace que te de algunas características de tu máquina, las mas básicas
			echo -e "\e[0m"
			VBoxManage showvminfo ${Menu[$opcion]} | grep --color=never Name:
			VBoxManage showvminfo ${Menu[$opcion]} | grep  --color=never Guest\ OS
			VBoxManage showvminfo ${Menu[$opcion]} | grep --color=never UUID: 
			VBoxManage showvminfo ${Menu[$opcion]} | grep --color=never Number\ of\ CPUs
			VBoxManage showvminfo ${Menu[$opcion]} | grep --color=never VRAM
			VBoxManage showvminfo ${Menu[$opcion]} | grep --color=never Memory\ size
			VBoxManage showvminfo ${Menu[$opcion]} | egrep NIC\ 1: | cut -d "," -f 2
			echo -e "\e[31m"
			echo "¿Quieres salir? [0 para salir]" 
			read salir
			if [ $salir -eq 0 ];
			then
				echo -e "\e[0m"
				break
			else
				echo "Seguiremos mostrando estadisticas."
				sleep 1
				clear
			fi
		else
			echo "Esa máquina no esta en la lista."
			sleep 1
			clear
		fi
	done
}
