#!/bin/bash
implantar_iso()
{
	clear
	while true;
	do
		echo -e "\e[96m"
		#Esto lista las maquinas virtuales que tenemos encendidas.
		VBoxManage list -s vms | cut -d '"' -f 2 > maquinas.txt
		typeset -a Menu
		exec 3< ./maquinas.txt
		Contador=1
		while read linea <&3; do
			echo "$Contador- $linea"
			Menu[$Contador]="$linea"		# Añadimos elementos al array
			Contador=$((Contador+1))	
		done
		echo "0- Salir"
		echo ""
		echo "Seleccione una Maquina Virtual."
		read opcion
		if [ $opcion -eq 0 ];
		then
			break
		elif [ $opcion -ge 1 -a $opcion -le ${#Menu[*]} ];
		then
			maquina=${Menu[$opcion]}
			echo "Maquina escogida."
			sleep 1
			break
		else
			echo "Esa máquina no esta en la lista."
			sleep 1
			clear
		fi
	done
	if [ $opcion -ne 0 ];
	then
		while true;
		do
			#Te da dos modos de implantarla,con el programa Dialog o escribiendo tu mismo la ruta, tiene que acabar con .iso
			clear
			echo "Busqueda de ISO"
			echo "---------------"
			echo "1- Modo Dialog"
			echo "2- Modo Texto"
			echo "0- Salir"
			echo "Seleccione un modo de Implantación de la ISO."
			read ISO
			if [ $ISO -eq 1 ];
			then
				dialog --fselect /home/$USER 0 0 2> ruta.txt
				clear
				echo -n "¿Es esta la ruta? " && cat ruta.txt && echo " [S para confirmar]"
				read respuesta
				if [ $respuesta = 'S' -o $respuesta = 's' ];
				then
					puerto=`VBoxManage showvminfo $maquina | egrep -o '[a-zA-Z0-9]{1,}.vdi' | wc -l`
					controlator=`VBoxManage showvminfo $maquina | grep 'Storage\ Controller\ Name' | cut -d " " -f 16`
					ruta=`cat ruta.txt`
					busqueda=`ls $ruta | grep -o '.iso'`
					if [ $busqueda = '.iso' ];
					then
						if [ $puerto -gt 1 -a $controlator = 'IDE' ];
						then
							echo "El controlador IDE solo soporta un puerto principal y otro secundario."
							sleep 1
						else
							VBoxManage storageattach $maquina --type dvddrive --storagectl $controlator --device 0 --port $puerto --medium $ruta
							break
						fi
					else
						echo "Eso no es una iso."
					fi
				fi
			elif [ $ISO -eq 2 ];
			then
				echo "Escriba la ruta de su ISO."
				read ruta
				clear
				echo -n "¿Es esta la ruta? " && cat ruta.txt && echo " [S para confirmar]"
				if [ $respuesta = 'S' -o $respuesta = 's' ];
				then
					puerto=`VBoxManage showvminfo $maquina | egrep -o '[a-zA-Z0-9]{1,}.vdi' | wc -l`
					controlator=`VBoxManage showvminfo $maquina | grep 'Storage\ Controller\ Name' | cut -d " " -f 16`
					ruta=`cat ruta.txt`
					busqueda=`ls $ruta | grep -o '.iso'`
					if [ $busqueda = '.iso' ];
					then
						if [ $puerto -gt 1 -a $controlador = "IDE" ];
						then
							echo "El controlador IDE solo soporta un puerto principal y otro secundario."
							sleep 1
						else
							VBoxManage storageattach $maquina --type dvddrive --storagectl $controlator --device 0 --port $puerto --medium $ruta
							break
						fi
					else
						echo "Eso no es una iso."
					fi

				fi
			elif [ $ISO -eq 0 ];
			then
				break
			fi
		done
	else
		break	
	fi	
}
