#!/bin/bash
iniciar_vm()
{
	clear
	while true;
	do
		#Esto lista las maquinas virtuales que tenemos en nuestro ordenador y lo redirigimos a un fichero de texto
		VBoxManage list -s vms | cut -d '"' -f 2 > maquinas.txt
		typeset -a Menu
		exec 3< ./maquinas.txt
		Contador=1
		echo -e "\e[32m"
		while read linea <&3; do
			echo "$Contador- $linea"
			Menu[$Contador]="$linea"		# Añadimos elementos al array
			Contador=$((Contador+1))	
		done
		echo "0- Salir"
		echo ""
		echo "Seleccione una Maquina Virtual."
		read opcion
		if [ $opcion -eq 0 ];
		then
			echo -e "\e[0m"
			break
		elif [ $opcion -ge 1 -a $opcion -le ${#Menu[*]} ];
		then
			echo -e "\e[0m"
			VBoxManage startvm ${Menu[$opcion]}
			break
		else
			echo "Esa máquina no esta en la lista."
			sleep 1
			clear
		fi
	done
}
