#!/bin/bash
#Este comando instalara feh.
instalar_feh()
{
	#Si detecta que feh está instalado no se volverá a instalar, en caso contrario si.
	instaladorfeh=`dpkg -s feh | egrep -o installed`
	if [ $instaladorfeh = "installed" ];
	then
		clear
		echo "feh esta instalado."
	else
		clear
		echo "¿Desea instalar el paquete feh?(Mostrador de fotos) [S para instalar] "
		read opcion
		if [ $opcion = 'S' -o $opcion = 's' ];
		then
			if [ $USER = "root" ];
			then
				apt-get update
				apt-get install feh
				clear
			else
				"No esta como root."
			fi
		else
			echo "No se instalará el programa."
		fi
	fi
}

#Este comando instalara virtualbox.
instalar_vbox()
{
	#Esto hace que si detecta que tienes vbox 5.2 o 6.0 instalado pues te lo detecte como instalado, sino se procede a instalarse automaticamente
	clear
	instalarvbox52=`dpkg -s virtualbox-5.2 | grep -o installed`
        instalarvbox6=`dpkg -s virtualbox-6.0 | grep -o installed`
        if [ $instalarvbox6 = "installed" -o $instalarvbox52 = "installed" ];
	then
		clear
                echo "VirtualBox esta instalado."
	else
		clear
		echo "VirtualBox no esta instalado"
		echo "¿Desea instalar VirtualBox 6.0 junto a sus repositorios? [S para continuar] "
		read opcion
		if [ $opcion = "S" -o $opcion = 's' ];
		then
			if [ $USER = 'root' ];
			then
				#Pregunta por tu distribución y te la añade a sources.list y las claves de virtualbox
				read -p "¿Cual es su distribucion de linux? [stretch,jessie...] " distribucion
				echo "deb https://download.virtualbox.org/virtualbox/debian $distribucion contrib" >> /etc/apt/sources.list
				wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add -
				wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | apt-key add -
				apt-get update
				clear
				echo "Instalando VirtualBox... Puede tardar varios minutos...."
				sleep 3
				apt-get install virtualbox-6.0
			else
				"No esta como root."
			fi
		else
			echo "No se instalará el programa."
		fi
	fi
}

instalar_dialog()
{
	#Si detecta que dialog está instalado no se volverá a instalar, en caso contrario si.
	clear
	dialog=`dpkg -s dialog | grep -o installed`
	if [ $dialog = "installed" ];
	then
		clear
		echo "Dialog esta instalado."
	else
		clear
		echo "Dialog no esta instalado."
		echo "¿Desea instalar Dialog? [S para continuar]"
		read opcion
		if [ $opcion = "S" -o $opcion = 's' ];
		then
			if [ $USER = 'root' ];
			then
				apt-get update
				apt-get install dialog
			else
				"No esta como root."
			fi
		else
			echo "No se instalará el programa."
		fi
	fi
		
}

instalar_figlet()
{
	#Si detecta que figlet está instalado no se instalará, en caso contrario si.
	clear
	figlet=`dpkg -s figlet | grep -o installed`
	if [ $figlet = "installed" ];
	then
		clear
		echo "Figlet esta instalado."
	else
		clear
		echo "Figlet no esta instalado."
		echo "¿Desea instalar Figlet? [S para continuar]"
		read opcion
		if [ $opcion = "S" -o $opcion = 's' ];
		then
			if [ $USER = 'root' ];
			then
				apt-get update
				apt-get install figlet
			else
				"No esta como root."
			fi
		else
			echo "No se instalará el programa."
		fi
	fi
		
}
