#!/bin/bash 
. ./FuncionesVirtualBox/ControlarMaquinasVBOX
. ./FuncionesVirtualBox/CreacionesMaquinasVBOX
. ./FuncionesVirtualBox/EliminarVBOX
. ./FuncionesVirtualBox/EstadisticasMaquinas
. ./FuncionesVirtualBox/ImplatarISOVBOX
. ./FuncionesVirtualBox/IniciarMaquinaVBOX
. ./FuncionesVirtualBox/Instaladores
. ./FuncionesVirtualBox/ModificarMaquinasVBOX
while true;
do
	clear
	instaladorfeh=`dpkg -s feh | egrep -o installed`
	instalarvbox=`dpkg -s virtualbox-6.0 | grep -o installed`
	dialog=`dpkg -s dialog | grep -o installed`
	figlet=`dpkg -s figlet | grep -o installed`
	echo -e "\e[0m"
	echo -e "\e[34m"
	figlet "VirtualBash"
	echo -e "\e[0m"
	echo -e "\e[42mEn este programa podremos usar VirtualBox a modo de comandos mediante VBoxManage\e[0m"
	echo ""
	echo "Seleccione una Opcion:"
	echo -e "\e[36mOpcion 1-Instalar Programas.(root)\e[0m"
	echo -e "\e[32mOpcion 2-Iniciar MV.\e[0m"
	echo -e "\e[97mOpcion 3-Crear MV.\e[0m"
	echo -e "\e[31mOpcion 4-Estadisticas MV.\e[0m"
	echo -e "\e[36mOpcion 5-Controlar MV.(Maquinas Activas)\e[0m"
	echo -e "\e[33mOpcion 6-Modificar MV.\e[0m"
	echo -e "\e[96mOpcion 7-Implantar ISO.\e[0m"
	echo -e "\e[37mOpcion 8-Eliminar MV.\e[0m"
	echo -e "\e[91mOpcion 0-Salir.\e[0m"
	read opcion
	if [ $opcion -eq 1 ];
	then
		if [ $USER = "root" ];
		then
			instalar_vbox
			instalar_feh
			instalar_dialog
			instalar_figlet
			clear
			echo "Todos los programas estan instalados."
			sleep 1
		else
			echo "No se podrá instalar los programas, no está como root."
			sleep 1
		fi
	elif [ $opcion -eq 2 ];
	then
		if [ $USER = "root" ];
		then
			
			echo "Está intentando iniciar una máquina virtual en modo root."
			sleep 1
		else
			iniciar_vm
		fi
	elif [ $opcion -eq 3 ];
	then
		if [ $USER = "root" ];
		then
			echo "Está intentando crear una máquina virtual en modo root."
			sleep 1
		else
			crear_vm
		fi
	elif [ $opcion -eq 4 ];
	then
		if [ $USER = "root" ];
		then
			echo "Está intentando ver las estadisticas de una máquina virtual en modo root."
			sleep 1
		else
			estadisticas_vm
		fi
	elif [ $opcion -eq 5 ];
	then
		if [ $USER = "root" ];
		then
			echo "Está intentando controlar una máquina virtual en modo root."
			sleep 1
		else
			controlar_vm
		fi
	elif [ $opcion -eq 6 ];
	then
		if [ $USER = "root" ];
		then
			echo "Está intentando modificar una máquina virtual en modo root."
			sleep 1
		else
			modificar_vm
		fi
	elif [ $opcion -eq 7 ];
	then
		if [ $USER = "root" ];
		then
			echo "Está intentando implantar una ISO en modo root."
			sleep 1
		else
			implantar_iso
		fi
	elif [ $opcion -eq 8 ];
	then
		if [ $USER = "root" ];
		then
			echo "Está intentando eliminar una máquina virtual en modo root."
			sleep 1
		else
			eliminar_vm
		fi
	elif [ $opcion -eq 0 ];
	then
		break
	fi
done
