#!/bin/bash 
. ./FuncionesVirtualBox/ControlarMaquinasVBOX
. ./FuncionesVirtualBox/CreacionesMaquinasVBOX
. ./FuncionesVirtualBox/EliminarVBOX
. ./FuncionesVirtualBox/EstadisticasMaquinas
. ./FuncionesVirtualBox/ImplatarISOVBOX
. ./FuncionesVirtualBox/IniciarMaquinaVBOX
. ./FuncionesVirtualBox/Instaladores
. ./FuncionesVirtualBox/ModificarMaquinasVBOX
while true;
do
	clear
	echo "Opcion 1-Instalar Programas.(root)"
	echo "Opcion 2-Iniciar MV."
	echo "Opcion 3-Crear MV."
	echo "Opcion 4-Estadisticas MV."
	echo "Opcion 5-Controlar MV.(Maquinas Activas)"
	echo "Opcion 6-Modificar MV."
	echo "Opcion 7-Implantar ISO."
	echo "Opcion 8-Eliminar MV."
	echo "Opcion 0-Salir."
	read opcion
	if [ $opcion -eq 1 ];
	then
		if [ $USER = "root" ];
		then
			instalar_vbox
			instalar_feh
			instalar_dialog
			clear
			echo "Todos los programas estan instalados."
			sleep 1
		else
			echo "No se podrá instalar los programas, no está como root."
			sleep 1
		fi
	elif [ $opcion -eq 2 ];
	then
		iniciar_vm
	elif [ $opcion -eq 3 ];
	then
		crear_vm
	elif [ $opcion -eq 4 ];
	then
		estadisticas_vm
	elif [ $opcion -eq 5 ];
	then
		controlar_vm
	elif [ $opcion -eq 6 ];
	then
		modificar_vm
	elif [ $opcion -eq 7 ];
	then
		implantar_iso
	elif [ $opcion -eq 8 ];
	then
		eliminar_vm
	elif [ $opcion -eq 0 ];
	then
		break
	fi
done
